global:
  scrape_interval:     15s  
  evaluation_interval: 15s   

  external_labels:
    monitor: 'phi-cygni-monitor'

rule_files:
  - 'prometheus.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'phi-cygni-prometheus-alertmanager-container:9093'

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['phi-cygni-prometheus-container:9090', 'phi-cygni-python-prometheus-client-container:8000']

  - job_name: 'nginx'

    static_configs:
      - targets: ['localhost:8016']

  - job_name: 'dev'

    static_configs:
      - targets: ['localhost:8008']

  - job_name: 'test'

    static_configs:
      - targets: ['localhost:8009']
